# Generated by Django 5.2.8 on 2026-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_iframe',
            field=models.TextField(default='', help_text="YouTube-тен 'Embed' кодын осында қойыңыз", verbose_name='YouTube IFrame коды'),
            preserve_default=False,
        ),
    ]
