# Generated by Django 5.2.8 on 2026-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_lesson_video_url_lesson_video_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_iframe',
            field=models.TextField(help_text="МАҢЫЗДЫ НҰСҚАУЛЫҚ: <br>1. YouTube-тен 'Embed' кодын көшіріп алыңыз.<br>2. Кодтың ішіне <b>id='player'</b> қосыңыз.<br>3. Сілтеме (src) соңына <b>?enablejsapi=1</b> қосыңыз.<br>Мысалы: &lt;iframe <b>id='player'</b> ... src='.../embed/ID<b>?enablejsapi=1</b>' ...&gt;&lt;/iframe&gt;", verbose_name='YouTube IFrame коды'),
        ),
    ]
