# Generated by Django 5.2.8 on 2026-05-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_iframe',
            field=models.TextField(help_text="МАҢЫЗДЫ НҰСҚАУЛЫҚ:1. <b>id='player'</b>2. ?enablejsapi=1", verbose_name='YouTube IFrame коды'),
        ),
    ]
