# Generated by Django 5.2.8 on 2026-06-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_question_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={},
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson_order')},
        ),
    ]
